services:
  ruby-app:
    build: .
    volumes:
      - ".:/app"
    working_dir: /app
    command: ["bash"]  # Starts an interactive shell (keeps the container alive)
    ports:
      - "3000:3000"  # Expose port 3000 for web access if you add a web server in the future
